EXTERNAL give_item(item_id, amount)
EXTERNAL remove_item(item_id, amount)
EXTERNAL change_money(amount)
EXTERNAL change_health(amount)
EXTERNAL change_energy(amount)
EXTERNAL set_value(key, value)
EXTERNAL add_value(key, amount)
EXTERNAL log(text)
EXTERNAL start_encounter(encounter_id)
EXTERNAL finish_encounter(outcome)
