from __future__ import annotations

from raygame.model.defs import ActionMethodDef, ActionPointDef, Condition, Effect, OutcomeDef
from raygame.model.enums import AreaName, Risk, ScreenName, Suit


MISSION_ACTIONS: dict[str, ActionPointDef] = {
    "fence": ActionPointDef(
        id="fence",
        title="铁丝网",
        description="锈味浓得像旧伤口。",
        screen=ScreenName.MISSION,
        area=AreaName.PERIMETER,
        methods=(
            ActionMethodDef(
                id="fence_reason",
                title="剪断",
                suits=(Suit.REASON,),
                difficulty=2,
                risk=Risk.LOW,
                description="挑最安静的那一截。",
                success=OutcomeDef("铁丝悄无声息地让开了。"),
                cost=OutcomeDef("进去是进去了，时间被拖慢。", (Effect("advance_clock", "alarm:1"),)),
                fail=OutcomeDef("铁丝狠狠咬了你一口。", (Effect("lose_health", 1),), completes=True),
            ),
            ActionMethodDef(
                id="fence_force",
                title="硬翻",
                suits=(Suit.FORCE,),
                difficulty=2,
                risk=Risk.MID,
                description="不想在外面耗。",
                success=OutcomeDef("你翻得足够快。"),
                cost=OutcomeDef("过去了，但手臂被拉开一道口子。", (Effect("lose_health", 1), Effect("insert_card", "bleeding"))),
                fail=OutcomeDef("你被卡住了一瞬，灯光扫了过来。", (Effect("lose_health", 1), Effect("advance_clock", "alarm:1"))),
            ),
            ActionMethodDef(
                id="fence_instinct",
                title="找缺口",
                suits=(Suit.INSTINCT,),
                difficulty=3,
                risk=Risk.LOW,
                description="先看哪里不是给人看的路。",
                success=OutcomeDef("你在铁丝网后面找到了荒草里的暗道。", (Effect("set_flag", "skip_guard"),)),
                cost=OutcomeDef("找到了，但你绕路太久。", (Effect("set_flag", "skip_guard"), Effect("advance_clock", "alarm:1"))),
                fail=OutcomeDef("没找到入口，只能回到铁丝网前。", (), completes=False),
            ),
        ),
    ),
    "guard": ActionPointDef(
        id="guard",
        title="巡逻守卫",
        description="脚步声很规律，视线一点也不。",
        screen=ScreenName.MISSION,
        area=AreaName.PERIMETER,
        conditions=(Condition("flag_not_set", "skip_guard"),),
        methods=(
            ActionMethodDef(
                id="guard_instinct",
                title="等待换班",
                suits=(Suit.INSTINCT,),
                difficulty=2,
                risk=Risk.LOW,
                conditions=(Condition("if_clue_reduce", "clue_c"),),
                description="跟着他们的节奏挪动。",
                success=OutcomeDef("你卡在换班盲区里穿了过去。"),
                cost=OutcomeDef("通过了，但脚步还是逼近了些。", (Effect("advance_clock", "alarm:1"),)),
                fail=OutcomeDef("你被灯光扫到，只能狼狈后撤。", (Effect("advance_clock", "alarm:2"),)),
            ),
            ActionMethodDef(
                id="guard_force",
                title="制服",
                suits=(Suit.FORCE,),
                difficulty=3,
                risk=Risk.HIGH,
                description="最快，也最脏。",
                success=OutcomeDef("守卫倒下了，钥匙也落进你手里。", (Effect("give_item", "guard_key"),)),
                cost=OutcomeDef("你制服了他，但噪音已经传出去了。", (Effect("give_item", "guard_key"), Effect("lose_health", 1), Effect("advance_clock", "alarm:1"))),
                fail=OutcomeDef("搏斗拖成了灾难。", (Effect("lose_health", 1), Effect("advance_clock", "alarm:2"))),
            ),
            ActionMethodDef(
                id="guard_empathy",
                title="引开",
                suits=(Suit.EMPATHY,),
                difficulty=2,
                risk=Risk.MID,
                description="假装这里还有别的麻烦。",
                success=OutcomeDef("他骂骂咧咧地离岗了。"),
                cost=OutcomeDef("他走开了，但你也跟着紧绷起来。", (Effect("add_stress", 1),)),
                fail=OutcomeDef("他没动，反倒更警觉了。", (Effect("advance_clock", "alarm:1"),)),
            ),
        ),
    ),
    "dog": ActionPointDef(
        id="dog",
        title="恶犬",
        description="它闻得到恐惧，也闻得到血。",
        screen=ScreenName.MISSION,
        area=AreaName.CORRIDOR,
        methods=(
            ActionMethodDef(
                id="dog_empathy",
                title="安抚",
                suits=(Suit.EMPATHY,),
                difficulty=3,
                risk=Risk.MID,
                description="先别盯着它的牙。",
                success=OutcomeDef("恶犬慢慢趴下了。"),
                cost=OutcomeDef("它退开了，但你花了太久。", (Effect("advance_clock", "alarm:1"),)),
                fail=OutcomeDef("它咬上来，牙齿像钉子。", (Effect("lose_health", 1), Effect("insert_card", "bite"))),
            ),
            ActionMethodDef(
                id="dog_force",
                title="硬闯",
                suits=(Suit.FORCE,),
                difficulty=2,
                risk=Risk.HIGH,
                description="忍痛冲过去。",
                success=OutcomeDef("你硬是从犬牙间挤了出去。"),
                cost=OutcomeDef("过去了，代价是肉被扯下一点。", (Effect("lose_health", 1), Effect("advance_clock", "alarm:2"))),
                fail=OutcomeDef("你被扑倒在地。", (Effect("lose_health", 2), Effect("advance_clock", "alarm:2"))),
            ),
            ActionMethodDef(
                id="dog_instinct",
                title="找食物引开",
                suits=(Suit.INSTINCT,),
                difficulty=2,
                risk=Risk.LOW,
                description="先找它比你更想要的东西。",
                success=OutcomeDef("恶犬叼着东西跑远了。"),
                cost=OutcomeDef("它被引走了，但你耽误了几分钟。", (Effect("advance_clock", "alarm:1"),)),
                fail=OutcomeDef("附近什么都没有，你只能另想办法。", (), completes=False),
            ),
        ),
    ),
    "control_room": ActionPointDef(
        id="control_room",
        title="灯控室",
        description="嗡鸣声让人牙酸。",
        screen=ScreenName.MISSION,
        area=AreaName.CORRIDOR,
        methods=(
            ActionMethodDef(
                id="control_room_reason",
                title="关灯",
                suits=(Suit.REASON,),
                difficulty=2,
                risk=Risk.LOW,
                description="把黑暗变成你的同伙。",
                success=OutcomeDef("整片冷库暗了下去。", (Effect("set_flag", "lights_off"),)),
                cost=OutcomeDef("灯是关了，但线路发出一声脆响。", (Effect("set_flag", "lights_off"), Effect("advance_clock", "alarm:1"))),
                fail=OutcomeDef("你碰出了短路。", (Effect("advance_clock", "alarm:2"),)),
            ),
            ActionMethodDef(
                id="control_room_instinct",
                title="搜查文件",
                suits=(Suit.INSTINCT,),
                difficulty=2,
                risk=Risk.LOW,
                description="先找纸，再找路。",
                success=OutcomeDef("冷库平面图露出一角。", (Effect("set_flag", "evidence_unlocked"),)),
                cost=OutcomeDef("你拿到了图，但时间被卷走了。", (Effect("set_flag", "evidence_unlocked"), Effect("advance_clock", "alarm:1"))),
                fail=OutcomeDef("文件翻得太急，什么都没留下。"),
            ),
        ),
    ),
    "hidden_door": ActionPointDef(
        id="hidden_door",
        title="冷藏间暗门",
        description="墙缝后面有股更冷的风。",
        screen=ScreenName.MISSION,
        area=AreaName.CORRIDOR,
        conditions=(Condition("has_clue", "clue_b"),),
        methods=(
            ActionMethodDef(
                id="hidden_door_instinct",
                title="检查",
                suits=(Suit.INSTINCT,),
                difficulty=1,
                risk=Risk.LOW,
                description="你知道这里多半有不该被人知道的门。",
                success=OutcomeDef("你摸到了直通冷库的捷径。", (Effect("set_flag", "freezer_shortcut"),)),
                cost=OutcomeDef("门找到了，但铰链还是响了。", (Effect("set_flag", "freezer_shortcut"), Effect("advance_clock", "alarm:1"))),
                fail=OutcomeDef("你只摸到一手冷水。"),
            ),
        ),
    ),
    "evidence": ActionPointDef(
        id="evidence",
        title="证据台",
        description="纸张上的血迹早就干了。",
        screen=ScreenName.MISSION,
        area=AreaName.FREEZER,
        conditions=(Condition("flag_set", "evidence_unlocked"),),
        methods=(
            ActionMethodDef(
                id="evidence_reason",
                title="仔细翻查",
                suits=(Suit.REASON,),
                difficulty=3,
                risk=Risk.LOW,
                description="别漏掉任何一页。",
                success=OutcomeDef("你拿到了账本。事情一下子不只是绑架。", (Effect("give_item", "ledger"),)),
                cost=OutcomeDef("账本到手了，但有人已经注意到少了东西。", (Effect("give_item", "ledger"), Effect("advance_clock", "alarm:1"))),
                fail=OutcomeDef("你只来得及看到几句模糊的名字。"),
            ),
            ActionMethodDef(
                id="evidence_instinct",
                title="快速扫一眼",
                suits=(Suit.INSTINCT,),
                difficulty=2,
                risk=Risk.LOW,
                description="先确认这里是不是值钱。",
                success=OutcomeDef("你知道乌鸦不是单纯的受害者。", (Effect("set_flag", "partial_truth"),)),
                cost=OutcomeDef("你抓到一点真相的边角。", (Effect("set_flag", "partial_truth"), Effect("advance_clock", "alarm:1"))),
                fail=OutcomeDef("纸太多，时间太少。"),
            ),
        ),
    ),
    "boss": ActionPointDef(
        id="boss",
        title="头目",
        description="他站在那里，像把整个冷库都买了下来。",
        screen=ScreenName.MISSION,
        area=AreaName.FREEZER,
        methods=(
            ActionMethodDef(
                id="boss_force",
                title="正面对峙",
                suits=(Suit.FORCE,),
                difficulty=4,
                risk=Risk.HIGH,
                description="赌一口狠气。",
                success=OutcomeDef("你把他砸倒在地。", (Effect("set_flag", "boss_force"),)),
                cost=OutcomeDef("你赢了，但人几乎散架。", (Effect("set_flag", "boss_force"), Effect("lose_health", 2), Effect("add_stress", 2))),
                fail=OutcomeDef("他的人把你按在地上。", (Effect("fail_run", "倒在冷库"),)),
            ),
            ActionMethodDef(
                id="boss_talk",
                title="谈判",
                suits=(Suit.EMPATHY,),
                difficulty=4,
                risk=Risk.HIGH,
                description="没有筹码也得先开口。",
                success=OutcomeDef("他松口了，但你几乎把身上的筹码都抛了出去。", (Effect("set_flag", "boss_deal"), Effect("spend_all_money", True))),
                cost=OutcomeDef("谈崩了一半。人可以带走，麻烦也一起带走。", (Effect("set_flag", "boss_deal"), Effect("advance_clock", "alarm:4"))),
                fail=OutcomeDef("头目笑了笑，抬手叫人。", (Effect("advance_clock", "alarm:4"),)),
            ),
            ActionMethodDef(
                id="boss_ledger",
                title="用账本谈判",
                suits=(Suit.EMPATHY, Suit.REASON),
                difficulty=2,
                risk=Risk.MID,
                conditions=(Condition("has_item", "ledger"),),
                description="把真相当武器。",
                success=OutcomeDef("账本逼得他退了一步。", (Effect("set_flag", "boss_ledger"), Effect("advance_clock", "heat:3"))),
                cost=OutcomeDef("他放人了，但记住了你的脸。", (Effect("set_flag", "boss_ledger"), Effect("advance_clock", "heat:3"), Effect("advance_clock", "alarm:1"))),
                fail=OutcomeDef("他想抢账本，场面变得更糟。", (Effect("advance_clock", "alarm:2"), Effect("add_stress", 2))),
            ),
            ActionMethodDef(
                id="boss_bypass",
                title="绕过",
                suits=(Suit.INSTINCT,),
                difficulty=2,
                risk=Risk.MID,
                conditions=(Condition("flag_set", "freezer_shortcut"),),
                description="别让他有机会抬头。",
                success=OutcomeDef("你贴着阴影滑了过去。", (Effect("set_flag", "boss_bypass"),)),
                cost=OutcomeDef("你绕开了他，但脚步已经被听见。", (Effect("set_flag", "boss_bypass"), Effect("advance_clock", "alarm:1"))),
                fail=OutcomeDef("你还是撞上了他的视线。", (Effect("advance_clock", "alarm:2"),)),
            ),
        ),
    ),
    "crow": ActionPointDef(
        id="crow",
        title="乌鸦",
        description="她抬起头时，眼神还是那样倔。",
        screen=ScreenName.MISSION,
        area=AreaName.FREEZER,
        methods=(
            ActionMethodDef(
                id="crow_reason",
                title="解绑",
                suits=(Suit.REASON,),
                difficulty=2,
                risk=Risk.LOW,
                description="先把结解开。",
                success=OutcomeDef("绳结松了，乌鸦终于能站起来。", (Effect("set_flag", "crow_rescued"),)),
                cost=OutcomeDef("你解开了她，但脚步声也越来越近。", (Effect("set_flag", "crow_rescued"), Effect("advance_clock", "alarm:1"))),
                fail=OutcomeDef("结打得太死，你急得手心发汗。", (Effect("add_stress", 1),), completes=False),
            ),
            ActionMethodDef(
                id="crow_empathy",
                title="对话",
                suits=(Suit.EMPATHY,),
                difficulty=1,
                risk=Risk.LOW,
                conditions=(Condition("flag_set", "crow_rescued"),),
                description="先听她说完。",
                success=OutcomeDef("乌鸦把偷账本的原因全说了出来。", (Effect("set_flag", "crow_talked"),)),
                cost=OutcomeDef("她说了真相，但你们已经没多少时间。", (Effect("set_flag", "crow_talked"), Effect("advance_clock", "alarm:1"))),
                fail=OutcomeDef("她只让你先走。"),
            ),
        ),
    ),
}

